version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

  tests:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py  

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"      

  
workflows:
  build_and_tests_deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
       - deploy:
           requires:
             - tests
           filters:
             branches:
               only: main
          
